import { useState } from 'react'
import { useOS } from '../context/OSContext'
import { profile, skills, experience } from '../data/profile'
import { projects } from '../data/projects'
import Icon from '../components/Icon'
import AppLayout, { PageHeading } from '../components/AppLayout'
import { ProjectArt } from './Projects'
function About() {
  const { openApp } = useOS()
  return <div className="about-content"><section className="about-hero"><div className="hero-copy"><span className="eyebrow"><span className="tiny-wave">✳</span> HELLO, WORLD. I'M</span><h1>Harsh Mishra<span>.</span></h1><h2>Developer by craft.<br/>Problem-solver by nature.</h2><p>{profile.description}</p><div className="hero-actions"><button className="button primary" onClick={() => openApp('projects')}><Icon name="folder" size={17}/>Explore my work<Icon name="arrow" size={16}/></button><button className="button" onClick={() => openApp('resume')}><Icon name="document" size={17}/>My resume</button></div><div className="hero-location"><Icon name="location" size={14}/>{profile.locationLabel}<span>·</span><span>Building for everywhere</span></div></div><div className="profile-art" aria-label="Harsh Mishra monogram"><div className="avatar-orbit orbit-one"/><div className="avatar-orbit orbit-two"/><span className="floating-tag tag-code"><Icon name="code" size={22}/></span><span className="floating-tag tag-spark"><Icon name="design" size={18}/></span><div className="profile-monogram">hm<span>.</span></div><div className="profile-role"><span className="status-dot"/>FULL STACK DEVELOPER</div><span className="orbit-dot"/></div></section>
    <section className="specialties"><div><span className="specialty-symbol"><Icon name="code" size={21}/></span><span><b>Full-stack development</b><small>From interface to infrastructure</small></span></div><div><span className="specialty-symbol"><Icon name="activity" size={21}/></span><span><b>AI & automation</b><small>Making the complex feel simple</small></span></div><div><span className="specialty-symbol"><Icon name="browser" size={21}/></span><span><b>Thoughtful experiences</b><small>Designed for people. Built to last.</small></span></div></section>
    <section className="featured-section"><div className="section-heading"><div><span className="eyebrow">A FEW THINGS I'VE BUILT</span><h3>Selected work</h3></div><button className="text-button" onClick={() => openApp('projects')}>View all projects <Icon name="arrow" size={15}/></button></div><div className="featured-grid">{projects.slice(0, 3).map(p => <button className="featured-project" key={p.id} onClick={() => openApp('projects', p.id)}><ProjectArt project={p} compact/><div className="featured-project-meta"><div><h4>{p.name}</h4><p>{p.type}</p></div><Icon name="external" size={16}/></div></button>)}</div></section>
  </div>
}
function Skills({ data }) {
  const [category, setCategory] = useState(data || 'All'), [query, setQuery] = useState('')
  const visible = Object.entries(skills).filter(([key]) => category === 'All' || key === category)
  return <div className="page-content"><PageHeading eyebrow="THE RIGHT TOOLS, THE RIGHT SOLUTIONS" title="My toolkit." description="Technologies I use to bring ideas to life — and keep learning along the way."/><div className="filter-row"><label className="inline-search"><Icon name="search" size={17}/><input placeholder="Find a technology" aria-label="Find a technology" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Skill category" value={category} onChange={e => setCategory(e.target.value)}><option>All</option>{Object.keys(skills).map(k => <option key={k}>{k}</option>)}</select></div>{visible.map(([name, items]) => { const filtered = items.filter(s => s.toLowerCase().includes(query.toLowerCase())); return filtered.length ? <section className="skill-category" key={name}><h3><Icon name="code" size={18}/>{name}<span>{filtered.length}</span></h3><div className="skills-grid">{filtered.map((s,i) => <div className="technology-card" key={s}><span style={{ '--tech-hue': `${(i * 39 + 190) % 360}` }}>{s.substring(0,2)}</span><b>{s}</b></div>)}</div></section> : null })}{!visible.some(([,s]) => s.some(x => x.toLowerCase().includes(query.toLowerCase()))) && <p className="empty-state">No technologies match your search.</p>}</div>
}
function Experience() { return <div className="page-content"><PageHeading eyebrow="LEARNING BY BUILDING" title="The journey so far." description="Different challenges. Shared curiosity. Real-world experience."/><div className="experience-timeline">{experience.map((e, i) => <article className="experience-card" key={e.company}><div className={`experience-marker ${e.color}`}><Icon name={e.icon} size={23}/></div><div><div className="experience-top"><span className="eyebrow">{e.company}</span><span className="subtle-badge">{e.duration}</span></div><h2>{e.role}</h2><p>{e.description}</p><div className="tags">{e.tags.map(t => <span key={t}>{t}</span>)}</div></div></article>)}</div><div className="soft-note"><Icon name="info" size={19}/><p>Every role is a chance to learn something new, take ownership, and make the next thing a little better.</p></div></div> }
function Education() { const e = profile.education; return <div className="page-content"><PageHeading eyebrow="ALWAYS A STUDENT" title="Built on curiosity." description="A foundation in computer science. A habit of learning beyond the classroom."/><article className="education-card"><span className="education-icon"><Icon name="education" size={37}/></span><div><span className="eyebrow">{e.graduation}</span><h2>{e.degree}</h2><p>{e.university} · {e.location}</p></div><div className="cgpa"><b>8.08</b><small>CGPA / 10</small></div></article><h3 className="content-subheading">Certifications & training</h3><div className="certificate-list">{profile.certifications.map(c => <article key={c}><Icon name="document" size={23}/><span>{c}</span><Icon name="check" size={18}/></article>)}</div><h3 className="content-subheading">Beyond the classroom</h3><div className="achievement-list">{profile.achievements.map(a => <div key={a}><span className="status-dot"/>{a}</div>)}</div></div> }
function Contact() {
  const { notify } = useOS(), [copied, setCopied] = useState(false), [name, setName] = useState(''), [email, setEmail] = useState(''), [message, setMessage] = useState('')
  const copy = async () => { try { await navigator.clipboard.writeText(profile.email); setCopied(true); setTimeout(() => setCopied(false), 2500); notify('Email copied', 'The next great conversation is one paste away.', 'mail') } catch { notify('Copy unavailable', 'You can select and copy the email address directly.', 'info') } }
  return <div className="page-content"><PageHeading eyebrow="GOOD WORK STARTS WITH A HELLO" title="Let's make something great." description="Have an idea, an opportunity, or just a good question? My inbox is open."/><div className="contact-layout"><section><div className="contact-card"><span className="contact-icon"><Icon name="mail" size={26}/></span><h3>Drop me a line</h3><a href={`mailto:${profile.email}`}>{profile.email}</a><button className="text-button" onClick={copy}><Icon name={copied ? 'check' : 'copy'} size={16}/>{copied ? 'Copied to clipboard' : 'Copy email address'}</button></div><a className="social-card" href={profile.github} target="_blank" rel="noopener noreferrer"><Icon name="code" size={24}/><div><b>Find me on GitHub</b><span>@harshmishra048</span></div><Icon name="external" size={18}/></a><p className="contact-caption">Full-stack development.<br/>Thoughtful collaboration.<br/>Something worth building.</p></section><form className="contact-form" onSubmit={e => { e.preventDefault(); const body = `Hi Harsh,\n\n${message}\n\n${name}\n${email}`; location.href = `mailto:${profile.email}?subject=${encodeURIComponent('Let’s connect — ' + name)}&body=${encodeURIComponent(body)}`; notify('Email draft prepared', 'Continue in your email application to send your message.', 'mail') }}><h3>Say hello</h3><label>Your name<input required maxLength="100" placeholder="How should I call you?" value={name} onChange={e => setName(e.target.value)}/></label><label>Email address<input type="email" required placeholder="you@example.com" value={email} onChange={e => setEmail(e.target.value)}/></label><label>What are you thinking?<textarea required maxLength="3000" rows="4" placeholder="Tell me a little about your idea…" value={message} onChange={e => setMessage(e.target.value)}/></label><button className="button primary" type="submit">Open email draft<Icon name="arrow" size={17}/></button><small>Opens your email app. Nothing is sent or stored here.</small></form></div></div>
}
export default function Portfolio({ page, data }) {
  return <AppLayout page={page} footer={{ skills: 'A growing toolkit. An ever-curious mindset.', experience: 'Experience verified from my resume', education: 'Learning, one challenge at a time', contact: 'One conversation can change everything' }[page]}>{page === 'about' ? <About/> : page === 'skills' ? <Skills key={data} data={data}/> : page === 'experience' ? <Experience/> : page === 'education' ? <Education/> : <Contact/>}</AppLayout>
}
