import { useEffect, useState } from 'react'
import { useOS } from '../context/OSContext'
import { projects } from '../data/projects'
import { profile } from '../data/profile'
import Icon from '../components/Icon'
import AppLayout, { PageHeading } from '../components/AppLayout'
export function ProjectArt({ project: p, compact = false }) {
  return <div className={`project-art ${p.color} art-${p.art} ${compact ? 'compact' : ''}`} aria-label={`${p.name} project illustration`}><span className="project-art-grid"/>{p.art === 'health' ? <><div className="art-wordmark"><span className="health-plus">+</span>medample<span className="art-wordmark-dot">.</span></div><div className="health-line"><svg viewBox="0 0 300 90"><path d="M0 50h65l15-17 17 35 24-63 25 78 22-33h132" fill="none" stroke="currentColor" strokeWidth="2"/></svg></div><span className="art-caption">HEALTHCARE, CONNECTED.</span></> : p.art === 'community' ? <><div className="community-orbit"/><div className="community-orbit second"/><div className="community-center"><Icon name="people" size={35}/></div><span className="community-node one">L</span><span className="community-node two">S</span><div className="art-project-name">Legacy<span>Sphere</span></div></> : p.art === 'signal' ? <><div className="signal-lines"><i/><i/><i/><i/><i/></div><Icon name="hand" size={compact ? 58 : 78}/><div className="suri-name">SURI<span>BEYOND WORDS.</span></div></> : <><div className="face-frame"><Icon name="scan" size={70}/></div><span className="art-caption">EXPRESSIONS, UNDERSTOOD.</span></>}</div>
}
export default function Projects({ data }) {
  const { notify } = useOS(), [selected, setSelected] = useState(data || null), [category, setCategory] = useState('All projects'), [query, setQuery] = useState('')
  useEffect(() => { if (data) setSelected(data) }, [data])
  const project = projects.find(p => p.id === selected)
  const visible = projects.filter(p => (category === 'All projects' || p.category === category) && (p.name + ' ' + p.tags.join(' ')).toLowerCase().includes(query.toLowerCase()))
  const openProject = p => { setSelected(p.id); notify('Project opened', `You're exploring ${p.name}.`, 'folder') }
  return <AppLayout page="projects" title={project?.name || 'Projects'} footer={`${projects.length} projects · Built with purpose`}>
    {project ? <article className="page-content project-detail"><button className="text-button back-button" onClick={() => setSelected(null)}><Icon name="back" size={16}/>All projects</button><ProjectArt project={project}/><div className="project-detail-heading"><div><span className="eyebrow">{project.type}</span><h1>{project.name}</h1><p>{project.subtitle}</p></div><span className="subtle-badge">{project.category}</span></div><div className="tags">{project.tags.map(t => <span key={t}>{t}</span>)}</div><section className="project-overview"><h3>The idea</h3><p>{project.detail}</p><h3>What it does</h3><ul>{project.features.map(f => <li key={f}><Icon name="check" size={17}/>{f}</li>)}</ul><h3>My contribution</h3><p>{project.role}</p></section><div className="project-link-note"><Icon name="info" size={21}/><div><b>Want a closer look?</b><p>Project-specific repository links, live demos, and screenshots weren't included in my resume. Browse my GitHub or get in touch for more details.</p></div></div><div className="hero-actions"><a className="button primary" href={profile.github} target="_blank" rel="noopener noreferrer"><Icon name="code" size={18}/>Visit my GitHub<Icon name="external" size={16}/></a><button className="button" onClick={() => { location.href = `mailto:${profile.email}?subject=${encodeURIComponent('Tell me more about ' + project.name)}` }}>Ask about this project</button></div><p className="illustration-note">Original concept illustration, not a screenshot of the live product.</p></article> : <div className="page-content"><PageHeading eyebrow="FROM AN IDEA TO SOMETHING REAL" title="Things I've built." description="A selection of projects at the intersection of useful technology and thoughtful design."/><div className="projects-filters"><div className="segmented-control">{['All projects','Full Stack','AI & ML'].map(c => <button key={c} className={category === c ? 'active' : ''} onClick={() => setCategory(c)}>{c}</button>)}</div><label className="inline-search"><Icon name="search" size={16}/><input aria-label="Search projects" placeholder="Search projects" value={query} onChange={e => setQuery(e.target.value)}/></label></div><div className="projects-grid">{visible.map(p => <button className="project-card" key={p.id} onClick={() => openProject(p)}><ProjectArt project={p}/><div className="project-card-body"><div className="project-card-heading"><h2>{p.name}</h2><Icon name="external" size={18}/></div><p>{p.description}</p><div className="tags">{p.tags.slice(0, 3).map(t => <span key={t}>{t}</span>)}</div></div></button>)}</div>{!visible.length && <div className="empty-state"><Icon name="search" size={36}/><h3>No projects found</h3><p>Try another name or technology.</p></div>}</div>}
  </AppLayout>
}
