import { useOS } from '../context/OSContext'
import { apps, getApp } from '../data/apps'
import { profile } from '../data/profile'
import Icon from './Icon'
export default function AppLayout({ page, children, title, trailing, footer }) {
  const { openApp } = useOS()
  return <div className="portfolio-layout"><aside className="app-sidebar"><div className="sidebar-profile"><span className="mini-avatar">HM</span><span><b>{profile.name}</b><small>Personal workspace</small></span></div><span className="sidebar-label">MY PORTFOLIO</span><nav>{apps.filter(a => a.group === 'Portfolio').map(a => <button className={page === a.id ? 'active' : ''} key={a.id} onClick={() => openApp(a.id)}><Icon name={a.icon} size={18}/><span>{a.name}</span>{page === a.id && <span className="nav-active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><p>GOOD IDEAS START<br/>WITH A CONVERSATION.</p><button onClick={() => openApp('contact')}>Let's connect <Icon name="arrow" size={17}/></button><hr/><button className="sidebar-settings" onClick={() => openApp('settings')}><Icon name="settings" size={17}/>Settings</button></div></aside><section className="app-main"><header className="app-toolbar"><div className="breadcrumbs"><Icon name="home" size={16}/><Icon name="right" size={13}/><span>Portfolio</span><Icon name="right" size={13}/><b>{title || getApp(page)?.name}</b></div>{trailing || <span className="toolbar-status"><span className="status-dot"/>Let's build something</span>}</header><div className="app-scroll">{children}</div><footer className="app-statusbar"><span><span className="status-dot"/>{footer || 'A little about the person behind the work'}</span><span>Made with curiosity & code <Icon name="code" size={13}/></span></footer></section></div>
}
export function PageHeading({ eyebrow, title, description, children }) { return <header className="page-heading">{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description && <p>{description}</p>}{children}</header> }
